### ISSUE TITLE
Content 

### ISSUE THREAD

**Issue by JeelRajodiya** [json-schema-org/tour#13]
> The work is being done in the `content` branch 

# Things to keep in mind
- Each step builds upon the previous one
- The reader should not need to look ahead to find any unknown definitions, it should be covered or should be at least mentioned
- Do not bore the reader, teach practical concepts first. 
- The steps should not be too long. They should be of appropriate length.
- Use some contexts for teaching the schema - API Design, Aviation, Finance etc.  
- Make the starting steps of the chapter intriguing so the reader keeps reading  
- Add a chapter summary after in the last steps if necessary 
- Teach through complex examples

# Topics to Cover 

> **Note:** This list will keep getting updated 

###  Basics

- [x] 1. JSON Schema Syntax and Structure 

### Overview of Basic Types 
- [x] 1. Boolean
- [x] 2. Numeric Type 
- [x] 3. String
- [x] 4. Object
- [x] 5. Array
- [x] 6. Specifying Constant Values 
- [x] 7. Null

### Generic Keywords 
- [x] 1. Defining Enumerated Values with enum Keyword 
- [x] 2. type Keyword
- [x] 3. $schema keyword 
- [x] 4. $id keyword 

 
### Strings
- [x] 1. Constraining the Length with minLength and maxLength
- [x] 2. Restricting String Values with enum
- [x] 3. Regular Expressions 

### Numeric Types
- [x] 1. Integer 
- [x] 2. Number
- [x] 3. Using enum with Integers and Numbers
- [x] 4. Restricting a Number to be Multiples of a Given Number - multipleOf keyword 
- [x] 5. exclusiveMinimum 
- [x] 6. exclusiveMaximum
- [x] 7. minimum
- [x] 8. maximum

### Arrays 
- [x] 1. Specifying types for array Items
- [x] 2. Tuple Validation
- [x] 3. Unique Items 
- [x] 4. Additional Items
- [x] 5. Unevaluated Items
- [x] 6. Using contains keyword
- [x] 7. Specifying Valid Array Items with enum
- [x] 8. minContains and maxContains
- [x] 9. Specifying the Length of an Array

### Objects 
- [x] 1. Creating Properties in Object
- [x] 2. Defining Pattern Properties 
- [x] 3. Defining Required Properties 
- [x] 4. minProperties and maxProperties
- [x] 6. Using The propertyNames Keyword 
- [x] 7. Handling the Extra Stuff with additionalProperties 
- [x] 8. Creating a Nested Data Structure
- [x] 9. Unevaluated Properties
- [x] 10. Extending closed schema

### Combining Schemas and Types
- [x] 1. Defining Subschemas with $defs Keyword
- [x] 2. Add External References - $ref Keyword
- [x] 3. Check for Valid Against All Subschemas (AND) - allOf
- [x] 4. Check for Valid Against Any Subschemas (OR) - anyOf
- [x] 5. Check for Valid Against Exactly One Subschemas (XOR) - oneOf
- [x] 6. Check for Not Valid Against The Given Schemas (NOT) - not
- [x] 7. Defining one property with multiple possible types using - [source](https://stackoverflow.com/questions/16241333/specify-a-value-can-be-a-string-or-null-with-json-schema)
- [x] 8. Recursive schemas

### Conditional Validation 
- [x] 1. Conditionally Requiring Certain Properties to be Present - dependentRequired
- [x] 2. Creating Dependent Schemas 
- [x] 3. If-Then-Else 
- [x] 4. Defining implications (A → B)

### Annotating with JSON Schema
- [x] 1. title and description keyword 
- [x] 2. Adding Comments with $comment Keyword 
- [x] 3. Using the default Keyword
- [x] 4. Using the examples Keyword
- [x] 5. Using the deprecated Keyword
- [x] 6. readOnly and writeOnly Properties in Objects
- [x] 7. Format Keyword in Strings

**Comment by JeelRajodiya** [comment]
## Some Similar Projects 

https://react.dev/learn
https://vuejs.org/tutorial/#step-1
https://learn.svelte.dev/tutorial/welcome-to-svelte
https://web.dev/learn/css/box-model
https://nextjs.org/learn/dashboard-app

**Comment by Puzzle88** [comment]
zoomus://us06web.zoom.us/join

**Comment by iamridoydey** [comment]
Is this completed?

**Comment by erosb** [comment]
I think yes - it was a placeholder issue when the project started for all content development.
