### ISSUE TITLE
dependentRequired tour step explanation/example reversed 

### ISSUE THREAD

**Issue by trimble** [json-schema-org/tour#51]
At https://tour.json-schema.org/content/05-Conditional-Validation/01-Ensuring-Conditional-Property-Presence, the explanation and example indicate that the way to encode "the age property is required if the name property is present" is
```
{
  "type": "object",
  "properties": {...},
  "dependentRequired": {
    "age": ["name"]
  }
}
```

...then the exercise asks for "if the creditCardNumber property is present, then the address property must also be present" and requires:
```
  "dependentRequired": {
    "creditCardNumber": [
      "address"
    ]
  },
```

In the documentation for dependentRequired at https://json-schema.org/understanding-json-schema/reference/conditionals#dependentRequired, "Each entry in the object maps from the name of a property, p, to an array of strings listing properties that are required if p is present" seems to indicate that the exercise is correct and the explanation/example are incorrect.

**Comment by JeelRajodiya** [comment]
Hi @trimble , Thank for the issue. I will update the incorrect explanation and examples. Please free feel to open more issues.
