### ISSUE TITLE
anyOf example is confusing

### ISSUE THREAD

**Issue by michaelmior** [json-schema-org/tour#59]
Currently the anyOf task asks for the following

> Modify the [schema](https://json-schema.org/learn/glossary#schema) given to you in the side editor to ensure that the document is valid if
> * It has either salary or hourlyRate property.
> * It has both employeeType and salary properties.

To me, the meaning of this was very unclear. I would suggest perhaps changing to the following:

> Modify the [schema](https://json-schema.org/learn/glossary#schema) given to you in the side editor to ensure that the document is valid if
> * It has the salary property.
> * It has the hourlyRate property.
> * It has both employeeType and salary properties.

This is still a little strange to me because the last item there is redundant.

**Comment by JeelRajodiya** [comment]
>This is still a little strange to me because the last item there is redundant.

Yes, It seems redundant to me as well. I believe, I have made an error in the last item.  

Thank you @michaelmior, I will update the task description. please feel free to open more issues
