### ISSUE TITLE
$ids shouldn't have extensions

### ISSUE THREAD

**Issue by jdesrosiers** [json-schema-org/tour#64]
In the $id and $schema lesson, the examples use a file extension (`*.schema.json`) for URIs that use `https:` URIs. The files schemas are stored in should have extensions, but not identifiers using `https:` URIs. `https://example.com/string` is an example of good practice. `https://example.com/person.schema.json` is not. It should be `https://example.com/person`.

**Comment by JeelRajodiya** [comment]
Thanks. I will update it
