### ISSUE TITLE
Implement Routes as per the chapter and the module

### ISSUE THREAD

**Issue by Piyusharora2003** [json-schema-org/tour#7]
The idea is to make routes based on the chapter number and the content inside it 

![image](https://github.com/json-schema-org/tour/assets/74443858/08988a72-778d-41d5-99a9-1b4d5553453b)

API / :chapterName(or Number)  /: moduleName(or number) 

API:  /Introduction/1   -> Why JSON Schema? Understanding JSON and Its Need for Schema
or 
API:  /1/1   -> Why JSON Schema? Understanding JSON and Its Need for Schema
or 
API: /Introduction/ WhyJsonSchema
(for the first and third we need to map the chapter to some string (chapter/module name/number)

I did like to implement the following . Looking forward for it .

**Comment by JeelRajodiya** [comment]
Hi @Piyusharora2003, Thanks for the issue. But I think the project will not have any backend since it is hosted on github pages. Also, the current outline of the content is likely to change. I am currently planning the project and its execution

**Comment by JeelRajodiya** [comment]
> I am referring for frontend routing only . I was willing for basic route implementation and mapping of data

Yes I understand. I appreciate your efforts. But, please do not rush. The project has just started and needs planning. Once everything is properly planned and working, I will be happy to accept contributors. Thanks.
