### ISSUE TITLE
give proper text color to a completed task and active task

### ISSUE THREAD

**Issue by JeelRajodiya** [json-schema-org/tour#76]
**Consider these three steps of Chapter 6:**
- Valid Against allOf the Subschemas (AND) **Not completed and not Active**
- Valid Against oneOf the Subschemas (XOR) **Not completed but Active**
- Valid Against anyOf the Subschemas (OR) **Completed but not active**

![image](https://github.com/user-attachments/assets/61f2b74e-b2c5-41a1-99a6-2abf5cc3d047)

Now when I click on the **Valid Against anyOf the Subschemas (OR)**, it will make it both active and completed. but the text color is such that, it is difficult to identify that it is active. We want to set the active and completed task to primary color. 

![image](https://github.com/user-attachments/assets/f5273f34-6e36-4cee-9957-14f787ae0df7)

**Comment by pavanydg** [comment]
can i work on this?

**Comment by JeelRajodiya** [comment]
@pavanydg Please go ahead
