### ISSUE TITLE
Feature: Prettify code in the code editor

### ISSUE THREAD

**Issue by JeelRajodiya** [json-schema-org/tour#77]
Currently, we have alt+shift+f shortcut to format the code in the code editor of the tour. 

Setup formatting the code in a timely manner (when the code in the editor is complete, meaning it is not an invalid json)

(e.g. It should format the code in the text editor every 1 second.)

**Comment by pavanydg** [comment]
can i work on this?

**Comment by JeelRajodiya** [comment]
I am planning to work on this issue by myself (because it needs can involve updating the layout of the project). If I decide to make it available for contributors, a **Available** tag will be added. Thanks for your interest.

**Comment by keys-i** [comment]
@JeelRajodiya  could we make this into GitHub action perhaps?

**Comment by JeelRajodiya** [comment]
A github workflow would be irrelevant to the issue. I have update the issue title and description for more clarification.

**Comment by JeelRajodiya** [comment]
I have update the issue description, The issue is now available for contributors.

**Comment by pavanydg** [comment]
@JeelRajodiya I would like to do this.

**Comment by JeelRajodiya** [comment]
@pavanydg please go ahead

**Comment by JeelRajodiya** [comment]
@pavanydg Are you still working on it?

**Comment by pavanydg** [comment]
@JeelRajodiya yeah will raise a pr soon.
