### ISSUE TITLE
Update UI to show appropriate feedback on the clearing the progress

### ISSUE THREAD

**Issue by JeelRajodiya** [json-schema-org/tour#84]
1. Go to the [tour](https://tour.json-schema.org/content/01-Getting-Started/01-Your-First-Schema)
2. Click on the settings button.
![image](https://github.com/user-attachments/assets/1188c8d7-a034-467b-ab08-be7646a7f59a)

3. Click on the Clear progress button and click Reset. 
4. It will show you a done button, which is confusing. 

Update the UI such that, when the user clicks on the RESET button, it will close the clear progress modal and shows some feedback that the progress has been cleared (i.e. a toast). 
Make sure to customize the toast theme according to the theme of the project, you can edit the theme of the toast in the [theme.ts](https://github.com/json-schema-org/tour/blob/main/app/styles/theme.ts) ([chakra docs](https://v2.chakra-ui.com/docs/components/modal/theming) may help)

**Comment by fudgemasterultra** [comment]
@JeelRajodiya This seems like a great first issue! I need to get the environment setup, but do you mind if I tackle this one?

**Comment by JeelRajodiya** [comment]
Yes please go ahead @fudgemasterultra

**Comment by fudgemasterultra** [comment]
@JeelRajodiya I have this in pr [#89 ](https://github.com/json-schema-org/tour/pull/89)
