### ISSUE TITLE
Create a link checker CI 

### ISSUE THREAD

**Issue by JeelRajodiya** [json-schema-org/tour#85]
Currently the tour has many links in the [/content](https://github.com/json-schema-org/tour/tree/main/content), Create a CI that is similar to what we have in the website repo ([workflow file](https://github.com/json-schema-org/website/blob/main/.github/workflows/link-checker.yml)), that creates an issue similar to [this one](https://github.com/json-schema-org/website/issues/986) with list of all the errored links in the project.

**Comment by heysujal** [comment]
Hi, I never worked on CI before, so I would like to work on this.

**Comment by JeelRajodiya** [comment]
sure @heysujal, go ahead

**Comment by heysujal** [comment]
I am still working and learning on how CI works. I am going through github docs.

**Comment by JeelRajodiya** [comment]
Thanks for the update!

**Comment by JeelRajodiya** [comment]
@heysujal, the workflow is failing. Can you help? https://github.com/json-schema-org/tour/issues/105
