### ISSUE TITLE
Update the home page 

### ISSUE THREAD

**Issue by JeelRajodiya** [json-schema-org/tour#92]
Related #72 

Currently the homepage has one button which is the direct link to the first step. We want to display all the links of the chapter in the home page. 

Update the home page as per the given design

figma Link: https://www.figma.com/design/w8ow79jE7lJucJt2zZTbcz/Tour-of-JSON-Schema?node-id=2303-39&t=HRYIgoqFZ2J30ggg-1 

Please try not to hardcode the links and chapter titles, You can get the title and links of the chapters using the [contentManager class ](https://github.com/json-schema-org/tour/blob/9a792081a13b3d567ae4bc01fe903be4e57f3d22/lib/contentManager.ts#L40)

**New Design**

![image](https://github.com/user-attachments/assets/04505183-f1b9-42a3-9240-5fc3687b0cd2)

**Comment by gregsdennis** [comment]
Shouldn't the styling match that of the main site?

**Comment by JeelRajodiya** [comment]
> Shouldn't the styling match that of the main site?
Yes it should, but I couldn't come up with a better design. We are only using the JSON Schema brand color to match with the theme.

**Comment by pavanydg** [comment]
@JeelRajodiya i will take this up. Please

**Comment by JeelRajodiya** [comment]
@pavanydg please go ahead!

**Comment by gregsdennis** [comment]
> Yes it should, but I couldn't come up with a better design. We are only using the JSON Schema brand color to match with the theme. 

Why can't you just use the same design and "A Tour of"?

**Comment by benjagm** [comment]
Like Greg I think we would benefit from adjusting the style / fonts to match the official website.

**Comment by JeelRajodiya** [comment]
@gregsdennis Do you mean something similar to this? 

![image](https://github.com/user-attachments/assets/ddfa6487-5ea0-4c88-8df0-d3af3beae8c9)

**Comment by gregsdennis** [comment]
That fits a lot better with our current design, yes.

**Comment by JeelRajodiya** [comment]
Great! 
> That fits a lot better with our current design, yes.

I will update the figma design properly and ping @pavanydg when it is ready.

**Comment by JeelRajodiya** [comment]
@pavanydg Please check the [figma design](https://www.figma.com/design/w8ow79jE7lJucJt2zZTbcz/Tour-of-JSON-Schema?node-id=2303-39&t=uNOnxYQgH7TV4w1p-1) I have updated the home page for both dark mode and light mode. you can start working on it.
