### ISSUE TITLE
[SEO]  404 page improve the SEO prespective 

### ISSUE THREAD

**Issue by AQIB-NAWAB** [json-schema-org/tour#99]
Custom "404 page" improve the user experience  as well as the SEO .
Currently it is default nextjs 404 page 
![image](https://github.com/user-attachments/assets/e7c7895e-ba2c-4b95-9daa-17332f6171f1)

**Comment by AQIB-NAWAB** [comment]
fixes #100

**Comment by JeelRajodiya** [comment]
Hello @AQIB-NAWAB, Thanks for the issue. Please avoid opening a PR before discussing on the issue.

**Comment by JeelRajodiya** [comment]
@AQIB-NAWAB I am making the designs for the 404 page, Would you like to make the page accordingly?

**Comment by AQIB-NAWAB** [comment]
@JeelRajodiya  sure please share the design

**Comment by JeelRajodiya** [comment]
Here is the design screenshot and [Figma link](https://www.figma.com/design/w8ow79jE7lJucJt2zZTbcz/Tour-of-JSON-Schema?node-id=3339-472&t=wf8HXkYRya35qB9Y-1)

Please make sure that the page is compatible to the current theme (dark/light)

![image](https://github.com/user-attachments/assets/c2f7e8fa-4411-4c77-9e2d-afd6230a2542)

**Comment by AQIB-NAWAB** [comment]
Hy @JeelRajodiya I update the 404 page for both theme 
Here is output
Light Theme
![image](https://github.com/user-attachments/assets/75ee27a0-f7d6-491f-b89c-4a33937ddbcf)
Dark Theme 
![image](https://github.com/user-attachments/assets/1cc2042b-3b3b-4520-987e-440963f72157)

**Comment by JeelRajodiya** [comment]
Please use the css variables for the colors defined in the global.css
https://github.com/json-schema-org/tour/blob/main/app/styles/globals.css#L59-L67

**Comment by AQIB-NAWAB** [comment]
fix #100

**Comment by AQIB-NAWAB** [comment]
> Please use the css variables for the colors defined in the global.css https://github.com/json-schema-org/tour/blob/main/app/styles/globals.css#L59-L67

okk

**Comment by AQIB-NAWAB** [comment]
@JeelRajodiya I replaced the value with variables from golbal css 
Here is ouput 
![image](https://github.com/user-attachments/assets/0a119657-9df9-489f-9849-0e97192ce226)
![image](https://github.com/user-attachments/assets/7847de37-ca59-408f-a428-feabb3fd1119)

**Comment by AQIB-NAWAB** [comment]
@JeelRajodiya I have made the changes , please review the PR
